name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - run: npm ci
      name: Install Dependencies
    - run: npx standard
      name: Run Standard
    - run: npm run coverage
      name: Run Tests
    - run: npx nyc report --reporter=text-lcov > lcov.info
      name: Generate Code Coverage
    - name: Report Code Coverage
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        path-to-lcov: lcov.info
